# Here's where you define experiment-specific hyperparameters.
# You can also create lists and group parameters together into nested sub-parts.
# In Python, this is all read as a dict.

#First go at creating a file of hyperparameters 
#Aug 2022 Peggy Bevan


# environment/computational parameters
seed: 32678456782       # random number generator seed (long integer value)
device: cuda
num_workers: 4 #number of parallel operations

# dataset parameters
basename: /home/pegbev/
#num_classes: 16

# training hyperparameters
#resnet requires this image size
image_size: [224, 224]
#num_epochs: 200
batch_size: 128 #arbitrary?
#learning_rate: 0.001
#weight_decay: 0.001